kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.19
  volumes:
  - name: cache
    path: /go
  commands:
  - go test -coverprofile=cover.out ./...
  - go tool cover -func=cover.out

- name: build linux/amd64
  image: golang:1.19
  volumes:
  - name: cache
    path: /go
  depends_on:
  - test
  environment:
    GOOS: linux
    GOARCH: amd64
  commands:
  - go build -o release/plugin-$GOOS-$GOARCH

- name: build linux/arm64
  image: golang:1.19
  volumes:
  - name: cache
    path: /go
  depends_on:
  - test
  environment:
    GOOS: linux
    GOARCH: arm64
  commands:
  - go build -o release/plugin-$GOOS-$GOARCH

- name: build darwin/amd64
  image: golang:1.19
  volumes:
  - name: cache
    path: /go
  depends_on:
  - test
  environment:
    GOOS: darwin
    GOARCH: amd64
  commands:
  - go build -o release/plugin-$GOOS-$GOARCH

- name: build darwin/arm64
  image: golang:1.19
  volumes:
  - name: cache
    path: /go
  depends_on:
  - test
  environment:
    GOOS: darwin
    GOARCH: arm64
  commands:
  - go build -o release/plugin-$GOOS-$GOARCH

- name: build windows/amd64
  image: golang:1.19
  volumes:
  - name: cache
    path: /go
  depends_on:
  - test
  environment:
    GOOS: windows
    GOARCH: amd64
  commands:
  - go build -o release/plugin-$GOOS-$GOARCH.exe

# uncomment when the `github_token` secret has been added
#
#- name: release
#  image: plugins/github-release
#  settings:
#    files:
#      - release/plugin-linux-amd64
#      - release/plugin-linux-arm64
#      - release/plugin-darwin-amd64
#      - release/plugin-darwin-arm64
#      - release/plugin-windows-amd64.exe
#    api_key:
#      from_secret: github_token
#  when:
#    ref:
#      - refs/tags/*

volumes:
- name: cache
  temp: {}

trigger:
  branch:
  - master
