FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -o /bin/go-convert-service ./cmd/server

FROM gcr.io/distroless/static-debian12
COPY --from=builder /bin/go-convert-service /go-convert-service
EXPOSE 8090
ENTRYPOINT ["/go-convert-service"]
