- step:
    identifier: ansibleplaybookb2fcf1
    name: Ansible_Playbook
    spec:
      image: plugins/ansible
      settings:
        become: "true"
        become_user: root
        check: "false"
        extra_vars: '{"var1":"value1","var2":"value2"}'
        forks: "5"
        inventory: inventory.ini
        limit: localhost
        list_hosts: ""
        playbook: example-playbook.yml
        skip_tags: debug
        start_at_task: ""
        tags: setup,deploy
        vault_id: ""
        vault_password: <secrets.getValue('vault-password')>
    timeout: ""
    type: Plugin
