pipeline {
    agent any
    stages {
        stage('Run PowerShell') {
            steps {
                powershell '''
                Write-Output "Running a PowerShell command"
                '''
            }
        }
    }
}