apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "yaml-converter.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  name: yaml-converter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      protocol: TCP
      targetPort: {{ .Values.service.grpcPort }}
    - name: http
      port: {{ .Values.service.httpPort }}
      protocol: TCP
      targetPort: {{ .Values.service.httpPort }}
  selector:
    {{- include "yaml-converter.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "yaml-converter.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  name: yaml-converter-headless
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      protocol: TCP
      targetPort: {{ .Values.service.grpcPort }}
    - name: http
      port: {{ .Values.service.httpPort }}
      protocol: TCP
      targetPort: {{ .Values.service.httpPort }}
  selector:
    {{- include "yaml-converter.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  clusterIP: None
  type: {{ .Values.service.type }}
