pipeline {
    agent any
    stages {
        stage("verify file") {
            steps {
                script {
                    verifySha1(
                        file: 'file.txt',
                        hash: '22596363b3de40b06f981fb85d82312e8c0ed511'
                    )
                }
            }
        }
    }
} 