pipeline {
    agent any

    tools {
        ant 'ant1'
    }

    stages {
        stage('Plugin Build') {
            steps {
                script {
                    // Perform the checkout
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: '*/main']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [],
                        submoduleCfg: [],
                        userRemoteConfigs: [[url: 'https://github.com/Anshika2203/CombinedAllBuilds.git']]
                    ])

                    withAnt {
                        sh 'ant build'
                    }
                }
            }
        }
    }
}