pipeline {
    agent any
    stages {
        stage("verify file") {
            steps {
                script {
                    verifySha256(
                        file: 'file.txt',
                        hash: 'a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447'
                    )
                }
            }
        }
    }
}  
