// Code generated by scripts/generate.js; DO NOT EDIT.

// Copyright 2022 Harness, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package yaml

import "github.com/drone/go-convert/internal/flexible"

// Cache defines pipeline caching behavior.
type Cache struct {
	Enabled        *flexible.Field[bool]     `json:"enabled" yaml:"enabled"`
	Key            string                    `json:"key,omitempty" yaml:"key,omitempty"`
	Paths          *flexible.Field[[]string] `json:"paths,omitempty" yaml:"paths,omitempty"`
	Policy         string                    `json:"policy,omitempty" yaml:"policy,omitempty"`
	Override       *flexible.Field[bool]     `json:"override,omitempty" yaml:"override,omitempty"`
	Connector      string                    `json:"connector,omitempty" yaml:"connector,omitempty"`
	Region         string                    `json:"region,omitempty" yaml:"region,omitempty"`
	BucketName     string                    `json:"bucket_name,omitempty" yaml:"bucket_name,omitempty"`
	ContainerName  string                    `json:"container_name,omitempty" yaml:"container_name,omitempty"`
	StorageAccount string                    `json:"storage_account,omitempty" yaml:"storage_account,omitempty"`
	User           *flexible.Field[int]      `json:"user,omitempty" yaml:"user,omitempty"`
	Resources      *ContainerResources       `json:"resources,omitempty" yaml:"resources,omitempty"`
}
