// Code generated by scripts/generate.js; DO NOT EDIT.

// Copyright 2022 Harness, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package yaml

import (
	"encoding/json"
	"github.com/drone/go-convert/internal/flexible"
)

type Resources struct {
	Limits *Limits `json:"limits,omitempty" yaml:"limits,omitempty"`
}

type Limits struct {
	Memory string `json:"memory,omitempty" yaml:"memory,omitempty"`
	CPU    string `json:"cpu,omitempty"    yaml:"cpu,omitempty"`
}

type Clone struct {
	Depth      *flexible.Field[int64]     `json:"depth,omitempty"`
	Disabled   bool   `json:"disabled"`
	Insecure   *flexible.Field[bool]      `json:"insecure,omitempty"`
	Lfs        *flexible.Field[bool]      `json:"lfs,omitempty"`
	Ref        *CloneRef `json:"ref,omitempty"`
	Strategy   string    `json:"strategy,omitempty"`
	Submodules *flexible.Field[bool]      `json:"submodules,omitempty"`
	Tags       *flexible.Field[bool]      `json:"tags,omitempty"`
	Trace      *flexible.Field[bool]      `json:"trace,omitempty"`
	CloneDir   string `json:"clonedir,omitempty"`
	Resources *Resources `json:"resources,omitempty"`
}

// UnmarshalJSON implement the json.Unmarshaler interface.
func (v *Clone) UnmarshalJSON(data []byte) error {
	var out1 bool
	var out2 = struct {
		Depth      *flexible.Field[int64]     `json:"depth,omitempty"`
		Disabled   bool      `json:"disabled"`
		Insecure   *flexible.Field[bool]      `json:"insecure,omitempty"`
		Lfs        *flexible.Field[bool]      `json:"lfs,omitempty"`
		Ref        *CloneRef `json:"ref,omitempty"`
		Strategy   string    `json:"strategy,omitempty"`
		Submodules *flexible.Field[bool]      `json:"submodules,omitempty"`
		Tags       *flexible.Field[bool]      `json:"tags,omitempty"`
		Trace      *flexible.Field[bool]      `json:"trace,omitempty"`
		CloneDir   string `json:"clonedir,omitempty"`
		Resources *Resources `json:"resources,omitempty"`
	}{}

	if err := json.Unmarshal(data, &out1); err == nil {
		v.Disabled = !out1
		return nil
	}

	if err := json.Unmarshal(data, &out2); err == nil {
		*v = out2
		return nil
	} else {
		return err
	}
}
