// Code generated by scripts/generate.js; DO NOT EDIT.

// Copyright 2022 Harness, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package yaml

import "encoding/json"

type Container struct {
	Args        Stringorslice     `json:"args,omitempty" yaml:"args,omitempty"`
	Connector   string            `json:"connector,omitempty" yaml:"connector,omitempty"`
	Cpu         string       `json:"cpu,omitempty" yaml:"cpu,omitempty"`
	Credentials *Credentials      `json:"credentials,omitempty" yaml:"credentials,omitempty"`
	Dns         Stringorslice     `json:"dns,omitempty" yaml:"dns,omitempty"`
	Entrypoint  Stringorslice     `json:"entrypoint,omitempty" yaml:"entrypoint,omitempty"`
	Env         map[string]string `json:"env,omitempty" yaml:"env,omitempty"`
	ExtraHosts  Stringorslice     `json:"extra-hosts,omitempty" yaml:"extra-hosts,omitempty"`
	Group       StringorInt       `json:"group,omitempty" yaml:"group,omitempty"`
	Image       string            `json:"image,omitempty" yaml:"image,omitempty"`
	Memory      string       `json:"memory,omitempty" yaml:"memory,omitempty"`
	Network     string            `json:"network,omitempty" yaml:"network,omitempty"`
	NetworkMode string            `json:"network-mode,omitempty" yaml:"network-mode,omitempty"`
	Ports       []string          `json:"ports,omitempty" yaml:"ports,omitempty"`
	Privileged  bool              `json:"privileged,omitempty" yaml:"privileged,omitempty"`
	Pull        string            `json:"pull,omitempty" yaml:"pull,omitempty"`
	ShmSize     StringorInt       `json:"shm-size,omitempty" yaml:"shm-size,omitempty"`
	User        StringorInt       `json:"user,omitempty" yaml:"user,omitempty"`
	Volumes     []*Mount          `json:"volumes,omitempty" yaml:"volumes,omitempty"`
	Workdir     string            `json:"workdir,omitempty" yaml:"workdir,omitempty"`
}

// UnmarshalJSON implement the json.Unmarshaler interface.
func (v *Container) UnmarshalJSON(data []byte) error {
	var out1 string
	var out2 = struct {
		Args        Stringorslice     `json:"args,omitempty" yaml:"args,omitempty"`
		Connector   string            `json:"connector,omitempty" yaml:"connector,omitempty"`
		Cpu         string       `json:"cpu,omitempty" yaml:"cpu,omitempty"`
		Credentials *Credentials      `json:"credentials,omitempty" yaml:"credentials,omitempty"`
		Dns         Stringorslice     `json:"dns,omitempty" yaml:"dns,omitempty"`
		Entrypoint  Stringorslice     `json:"entrypoint,omitempty" yaml:"entrypoint,omitempty"`
		Env         map[string]string `json:"env,omitempty" yaml:"env,omitempty"`
		ExtraHosts  Stringorslice     `json:"extra-hosts,omitempty" yaml:"extra-hosts,omitempty"`
		Group       StringorInt       `json:"group,omitempty" yaml:"group,omitempty"`
		Image       string            `json:"image,omitempty" yaml:"image,omitempty"`
		Memory      string       `json:"memory,omitempty" yaml:"memory,omitempty"`
		Network     string            `json:"network,omitempty" yaml:"network,omitempty"`
		NetworkMode string            `json:"network-mode,omitempty" yaml:"network-mode,omitempty"`
		Ports       []string          `json:"ports,omitempty" yaml:"ports,omitempty"`
		Privileged  bool              `json:"privileged,omitempty" yaml:"privileged,omitempty"`
		Pull        string            `json:"pull,omitempty" yaml:"pull,omitempty"`
		ShmSize     StringorInt       `json:"shm-size,omitempty" yaml:"shm-size,omitempty"`
		User        StringorInt       `json:"user,omitempty" yaml:"user,omitempty"`
		Volumes     []*Mount          `json:"volumes,omitempty" yaml:"volumes,omitempty"`
		Workdir     string            `json:"workdir,omitempty" yaml:"workdir,omitempty"`
	}{}

	if err := json.Unmarshal(data, &out1); err == nil {
		v.Image = out1
		return nil
	}

	if err := json.Unmarshal(data, &out2); err == nil {
		*v = out2
		return nil
	} else {
		return err
	}
}
