// Code generated by scripts/generate.js; DO NOT EDIT.

// Copyright 2022 Harness, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package yaml

type Input struct {
	Default     interface{} `json:"default,omitempty" yaml:"default,omitempty"`
	Description string      `json:"description,omitempty" yaml:"description,omitempty"`
	Enum        interface{} `json:"enum,omitempty" yaml:"enum,omitempty"`
	Items       interface{} `json:"items,omitempty" yaml:"items,omitempty"`
	Mask        bool        `json:"mask,omitempty" yaml:"mask,omitempty"`
	Options     interface{} `json:"options,omitempty" yaml:"options,omitempty"`
	Pattern     string      `json:"pattern,omitempty" yaml:"pattern,omitempty"`
	Required    bool        `json:"required,omitempty" yaml:"required,omitempty"`
	Type        string      `json:"type,omitempty" yaml:"type,omitempty"`
	Value       interface{} `json:"value,omitempty" yaml:"value,omitempty"`
}