// Code generated by scripts/generate.js; DO NOT EDIT.

// Copyright 2022 Harness, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package yaml

import (
	"encoding/json"
	"fmt"
)

// MachineImage defines machine size values.
type MachineSize string

// MachineSize enumeration.
const (
	MachineSizeNone    MachineSize = ""
	MachineSizeFlex    MachineSize = "flex"
	MachineSizeSmall   MachineSize = "small"
	MachineSizeMedium  MachineSize = "medium"
	MachineSizeLarge   MachineSize = "large"
	MachineSizeXlarge  MachineSize = "xlarge"
	MachineSizeXxlarge MachineSize = "xxlarge"
)

// UnmarshalJSON unmashals a quoted json string to the enum value.
func (e *MachineSize) UnmarshalJSON(b []byte) error {
	var v string
	json.Unmarshal(b, &v)
	switch v {
	case "":
		*e = MachineSizeNone
	case "flex":
		*e = MachineSizeFlex
	case "small":
		*e = MachineSizeSmall
	case "medium":
		*e = MachineSizeMedium
	case "large":
		*e = MachineSizeLarge
	case "xlarge":
		*e = MachineSizeXlarge
	case "xxlarge":
		*e = MachineSizeXxlarge
	default:
		if IsExpression(v) {
			*e = MachineSize(v)
		} else {
			return fmt.Errorf("invalid MachineSize: %s", v)
		}
	}
	return nil
}
