// Code generated by scripts/generate.js; DO NOT EDIT.

// Copyright 2022 Harness, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package yaml

import "time"

type Pipeline struct {
	Barriers    []string          `json:"barriers,omitempty" yaml:"barriers,omitempty"`
	Clone       *Clone            `json:"clone,omitempty" yaml:"clone,omitempty"`
	Concurrency *Concurrency      `json:"concurrency,omitempty" yaml:"concurrency,omitempty"`
	Default     interface{}       `json:"default,omitempty" yaml:"default,omitempty"`
	Env         map[string]string `json:"env,omitempty" yaml:"env,omitempty"`
	Environment *EnvironmentRef   `json:"environment,omitempty" yaml:"environment,omitempty"`
	Id          string            `json:"identifier,omitempty" `
	If          string            `json:"if,omitempty" yaml:"if,omitempty"`
	Inputs      map[string]*Input `json:"Inputs,omitempty" `
	Jobs        map[string]*Stage `json:"jobs,omitempty" yaml:"jobs,omitempty"`
	Name        string            `json:"name,omitempty" yaml:"name,omitempty"`
	On          *On               `json:"on,omitempty" yaml:"on,omitempty"`
	Permissions *Permissions      `json:"permissions,omitempty" yaml:"permissions,omitempty"`
	Repo        *Repository       `json:"repo,omitempty" yaml:"repo,omitempty"`
	Service     *ServiceRef       `json:"service,omitempty" yaml:"service,omitempty"`
	Stages      []*Stage          `json:"stages,omitempty" yaml:"stages"`
	Status      *Status           `json:"status,omitempty" yaml:"status,omitempty"`
	Timeout     time.Duration     `json:"timeout,omitempty" yaml:"timeout,omitempty"`
}
