// Code generated by scripts/generate.js; DO NOT EDIT.

// Copyright 2022 Harness, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package yaml

type Schema struct {
	Action         *Template              `json:"action,omitempty"`
	Concurrency    *Concurrency           `json:"concurrency,omitempty"`
	Defaults       map[string]interface{} `json:"defaults,omitempty"`
	Env            map[string]string      `json:"env,omitempty"`
	Environment    *Environment           `json:"environment,omitempty"`
	Infrastructure *InfraSchema           `json:"infrastructure,omitempty"`
	Inputset       map[string]interface{} `json:"inputset,omitempty"`
	Jobs           map[string]*Stage      `json:"jobs,omitempty"`
	Name           string                 `json:"name,omitempty"`
	On             *On                    `json:"on,omitempty"`
	Permissions    *Permissions           `json:"permissions,omitempty"`
	Pipeline       *Pipeline              `json:"pipeline,omitempty"`
	Service        *Service               `json:"service,omitempty"`
	Template       *Template              `json:"template,omitempty"`
	Version        StringorInt            `json:"version,omitempty"`
}
