// Code generated by scripts/generate.js; DO NOT EDIT.

// Copyright 2022 Harness, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package yaml

import (
	"encoding/json"

	"github.com/drone/go-convert/internal/flexible"
)

type ServiceItem struct {
	Id   string                 `json:"id,omitempty"`
	With map[string]interface{} `json:"with,omitempty"`
	Ref  string                 `json:"ref,omitempty"` // git branch reference
	Type string                 `json:"type,omitempty"` // Deployment Type: Kubernetes, Helm, etc.
}	

// UnmarshalJSON implements json.Unmarshaler for ServiceItem.
// Handles: string "service1" or object {id: "service1", with: {...}}
func (s *ServiceItem) UnmarshalJSON(data []byte) error {
	// Try as simple string first
	var str string
	if err := json.Unmarshal(data, &str); err == nil {
		s.Id = str
		s.With = nil
		return nil
	}

	// Try as full object
	type Alias ServiceItem
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*s = ServiceItem(alias)
	return nil
}

// MarshalJSON implements json.Marshaler for ServiceItem.
// Outputs: string "service1" if no With, or object {id: "service1", with: {...}} if With exists
func (s ServiceItem) MarshalJSON() ([]byte, error) {
	// If no With and no Ref, marshal as simple string
	if len(s.With) == 0 && s.Ref == ""  && s.Type == "" {
		return json.Marshal(s.Id)
	}
	// Otherwise marshal as full object
	type Alias ServiceItem
	return json.Marshal((Alias)(s))
}

type ServiceRef struct {
	Type string `json:"type,omitempty"` // Deployment Type: Kubernetes, Helm, etc.
	Items        []*ServiceItem        `json:"items,omitempty"`
	Parallel     *flexible.Field[bool] `json:"parallel,omitempty"`
	MultiService bool                  `json:"-"` // Don't serialize this field
}

// UnmarshalJSON implements json.Unmarshaler for ServiceRef.
// Handles:
// - Single string: "service1"
// - Array of strings: ["service1", "service2"]
// - Object with items: {items: [...], parallel: true}
func (v *ServiceRef) UnmarshalJSON(data []byte) error {
	// Try as single string
	var str string
	if err := json.Unmarshal(data, &str); err == nil {
		v.Items = []*ServiceItem{{Id: str}}
		v.MultiService = false
		return nil
	}

	// Try as array of strings/items
	var arr []json.RawMessage
	if err := json.Unmarshal(data, &arr); err == nil {
		v.Items = make([]*ServiceItem, 0, len(arr))
		for _, raw := range arr {
			var item ServiceItem
			if err := json.Unmarshal(raw, &item); err != nil {
				return err
			}
			v.Items = append(v.Items, &item)
		}
		v.MultiService = len(v.Items) > 1
		return nil
	}

	// Try as full object with items field
	var out = struct {
		Items    []*ServiceItem        `json:"items,omitempty"`
		Parallel *flexible.Field[bool] `json:"parallel,omitempty"`
	}{}
	if err := json.Unmarshal(data, &out); err != nil {
		return err
	}
	v.Items = out.Items
	v.Parallel = out.Parallel
	v.MultiService = len(v.Items) > 1
	return nil
}

// MarshalJSON implements json.Marshaler for ServiceRef.
// Outputs:
// - Single string if one item without With and not MultiService: "service1"
// - Object with items if MultiService: {items: [...]} or {items: [...], parallel: true}
func (v *ServiceRef) MarshalJSON() ([]byte, error) {
	// Single item without With and not forced to be multi-service
	if len(v.Items) == 1 && !v.MultiService && v.Parallel == nil {
		item := v.Items[0]
		if item.Type == "" {
			item.Type = v.Type
		}
		return json.Marshal(item)
	}

	// Multi-service - always use items format
	type Alias ServiceRef
	return json.Marshal((*Alias)(v))
}
