// Code generated by scripts/generate.js; DO NOT EDIT.

// Copyright 2022 Harness, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package yaml

import "encoding/json"

type Output struct {
	Name  string `json:"name,omitempty"      yaml:"name,omitempty"`
	Alias string `json:"alias,omitempty" yaml:"alias,omitempty"`
	Mask  bool   `json:"mask,omitempty" yaml:"mask,omitempty"`
}

type StepRun struct {
	Container *Container        `json:"container,omitempty" yaml:"container,omitempty"`
	Env       map[string]interface{} `json:"env,omitempty" yaml:"env,omitempty"`
	Report    *ReportList       `json:"report,omitempty" yaml:"report,omitempty"`
	Script    Stringorslice     `json:"script,omitempty" yaml:"script,omitempty"`
	Shell     string            `json:"shell,omitempty" yaml:"shell,omitempty"`
	Outputs   []*Output          `json:"output,omitempty" yaml:"output,omitempty"`
	With      map[string]interface{} `json:"with,omitempty" yaml:"with,omitempty"`
}


// UnmarshalJSON implement the json.Unmarshaler interface.
func (v *StepRun) UnmarshalJSON(data []byte) error {
	var out1 Stringorslice
	var out2 = struct {
		Container *Container        `json:"container,omitempty" yaml:"container,omitempty"`
		Env       map[string]interface{} `json:"env,omitempty" yaml:"env,omitempty"`
		Report    *ReportList       `json:"report,omitempty" yaml:"report,omitempty"`
		Script    Stringorslice     `json:"script,omitempty" yaml:"script,omitempty"`
		Shell     string            `json:"shell,omitempty" yaml:"shell,omitempty"`
		Outputs   []*Output          `json:"output,omitempty" yaml:"output,omitempty"`
		With      map[string]interface{} `json:"with,omitempty" yaml:"with,omitempty"`
	}{}

	if err := json.Unmarshal(data, &out1); err == nil {
		v.Script = out1
		return nil
	}

	if err := json.Unmarshal(data, &out2); err == nil {
		*v = out2
		return nil
	} else {
		return err
	}
}
