// Code generated by scripts/generate.js; DO NOT EDIT.

// Copyright 2022 Harness, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package yaml

type StepClone struct {
	Clean                  bool      `json:"clean,omitempty"`
	Connector              string    `json:"connector,omitempty"`
	Depth                  int64     `json:"depth,omitempty"`
	Disabled               bool      `json:"disabled,omitempty"`
	Filter                 string    `json:"filter,omitempty"`
	Insecure               bool      `json:"insecure,omitempty"`
	Lfs                    bool      `json:"lfs,omitempty"`
	Path                   string    `json:"path,omitempty"`
	Ref                    *CloneRef `json:"ref,omitempty"`
	Repo                   string    `json:"repo,omitempty"`
	SetSafeDirectory       bool      `json:"set-safe-directory,omitempty"`
	SparseCheckout         string    `json:"sparse-checkout,omitempty"`
	SparseCheckoutConeMode string    `json:"sparse-checkout-cone-mode,omitempty"`
	Strategy               string    `json:"strategy,omitempty"`
	Submodules             bool      `json:"submodules,omitempty"`
	Tags                   bool      `json:"tags,omitempty"`
	Trace                  bool      `json:"trace,omitempty"`
}
