// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: go_convert_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoConvertService_ConvertPipeline_FullMethodName = "/io.harness.pms.conversion.proto.GoConvertService/ConvertPipeline"
	GoConvertService_ConvertTemplate_FullMethodName = "/io.harness.pms.conversion.proto.GoConvertService/ConvertTemplate"
	GoConvertService_ConvertInputSet_FullMethodName = "/io.harness.pms.conversion.proto.GoConvertService/ConvertInputSet"
	GoConvertService_ConvertTrigger_FullMethodName  = "/io.harness.pms.conversion.proto.GoConvertService/ConvertTrigger"
	GoConvertService_GetChecksum_FullMethodName     = "/io.harness.pms.conversion.proto.GoConvertService/GetChecksum"
)

// GoConvertServiceClient is the client API for GoConvertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoConvertServiceClient interface {
	ConvertPipeline(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
	ConvertTemplate(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
	ConvertInputSet(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
	ConvertTrigger(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
	GetChecksum(ctx context.Context, in *ChecksumRequest, opts ...grpc.CallOption) (*ChecksumResponse, error)
}

type goConvertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoConvertServiceClient(cc grpc.ClientConnInterface) GoConvertServiceClient {
	return &goConvertServiceClient{cc}
}

func (c *goConvertServiceClient) ConvertPipeline(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, GoConvertService_ConvertPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goConvertServiceClient) ConvertTemplate(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, GoConvertService_ConvertTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goConvertServiceClient) ConvertInputSet(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, GoConvertService_ConvertInputSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goConvertServiceClient) ConvertTrigger(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, GoConvertService_ConvertTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goConvertServiceClient) GetChecksum(ctx context.Context, in *ChecksumRequest, opts ...grpc.CallOption) (*ChecksumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChecksumResponse)
	err := c.cc.Invoke(ctx, GoConvertService_GetChecksum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoConvertServiceServer is the server API for GoConvertService service.
// All implementations must embed UnimplementedGoConvertServiceServer
// for forward compatibility.
type GoConvertServiceServer interface {
	ConvertPipeline(context.Context, *ConvertRequest) (*ConvertResponse, error)
	ConvertTemplate(context.Context, *ConvertRequest) (*ConvertResponse, error)
	ConvertInputSet(context.Context, *ConvertRequest) (*ConvertResponse, error)
	ConvertTrigger(context.Context, *ConvertRequest) (*ConvertResponse, error)
	GetChecksum(context.Context, *ChecksumRequest) (*ChecksumResponse, error)
	mustEmbedUnimplementedGoConvertServiceServer()
}

// UnimplementedGoConvertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoConvertServiceServer struct{}

func (UnimplementedGoConvertServiceServer) ConvertPipeline(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertPipeline not implemented")
}
func (UnimplementedGoConvertServiceServer) ConvertTemplate(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertTemplate not implemented")
}
func (UnimplementedGoConvertServiceServer) ConvertInputSet(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertInputSet not implemented")
}
func (UnimplementedGoConvertServiceServer) ConvertTrigger(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertTrigger not implemented")
}
func (UnimplementedGoConvertServiceServer) GetChecksum(context.Context, *ChecksumRequest) (*ChecksumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChecksum not implemented")
}
func (UnimplementedGoConvertServiceServer) mustEmbedUnimplementedGoConvertServiceServer() {}
func (UnimplementedGoConvertServiceServer) testEmbeddedByValue()                          {}

// UnsafeGoConvertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoConvertServiceServer will
// result in compilation errors.
type UnsafeGoConvertServiceServer interface {
	mustEmbedUnimplementedGoConvertServiceServer()
}

func RegisterGoConvertServiceServer(s grpc.ServiceRegistrar, srv GoConvertServiceServer) {
	// If the following call panics, it indicates UnimplementedGoConvertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoConvertService_ServiceDesc, srv)
}

func _GoConvertService_ConvertPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoConvertServiceServer).ConvertPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoConvertService_ConvertPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoConvertServiceServer).ConvertPipeline(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoConvertService_ConvertTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoConvertServiceServer).ConvertTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoConvertService_ConvertTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoConvertServiceServer).ConvertTemplate(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoConvertService_ConvertInputSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoConvertServiceServer).ConvertInputSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoConvertService_ConvertInputSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoConvertServiceServer).ConvertInputSet(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoConvertService_ConvertTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoConvertServiceServer).ConvertTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoConvertService_ConvertTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoConvertServiceServer).ConvertTrigger(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoConvertService_GetChecksum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChecksumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoConvertServiceServer).GetChecksum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoConvertService_GetChecksum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoConvertServiceServer).GetChecksum(ctx, req.(*ChecksumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoConvertService_ServiceDesc is the grpc.ServiceDesc for GoConvertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoConvertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.harness.pms.conversion.proto.GoConvertService",
	HandlerType: (*GoConvertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertPipeline",
			Handler:    _GoConvertService_ConvertPipeline_Handler,
		},
		{
			MethodName: "ConvertTemplate",
			Handler:    _GoConvertService_ConvertTemplate_Handler,
		},
		{
			MethodName: "ConvertInputSet",
			Handler:    _GoConvertService_ConvertInputSet_Handler,
		},
		{
			MethodName: "ConvertTrigger",
			Handler:    _GoConvertService_ConvertTrigger_Handler,
		},
		{
			MethodName: "GetChecksum",
			Handler:    _GoConvertService_GetChecksum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_convert_service.proto",
}
