// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/go_convert_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_PIPELINE  EntityType = 0
	EntityType_TEMPLATE  EntityType = 1
	EntityType_INPUT_SET EntityType = 2
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "PIPELINE",
		1: "TEMPLATE",
		2: "INPUT_SET",
	}
	EntityType_value = map[string]int32{
		"PIPELINE":  0,
		"TEMPLATE":  1,
		"INPUT_SET": 2,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_go_convert_service_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_proto_go_convert_service_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_proto_go_convert_service_proto_rawDescGZIP(), []int{0}
}

type ConvertRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EntityType         EntityType             `protobuf:"varint,1,opt,name=entity_type,json=entityType,proto3,enum=io.harness.pms.conversion.proto.EntityType" json:"entity_type,omitempty"`
	Yaml               string                 `protobuf:"bytes,2,opt,name=yaml,proto3" json:"yaml,omitempty"`
	TemplateRefMapping map[string]string      `protobuf:"bytes,3,rep,name=template_ref_mapping,json=templateRefMapping,proto3" json:"template_ref_mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PipelineRefMapping map[string]string      `protobuf:"bytes,4,rep,name=pipeline_ref_mapping,json=pipelineRefMapping,proto3" json:"pipeline_ref_mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_proto_go_convert_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_go_convert_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_proto_go_convert_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertRequest) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_PIPELINE
}

func (x *ConvertRequest) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

func (x *ConvertRequest) GetTemplateRefMapping() map[string]string {
	if x != nil {
		return x.TemplateRefMapping
	}
	return nil
}

func (x *ConvertRequest) GetPipelineRefMapping() map[string]string {
	if x != nil {
		return x.PipelineRefMapping
	}
	return nil
}

type ConvertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yaml          string                 `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertResponse) Reset() {
	*x = ConvertResponse{}
	mi := &file_proto_go_convert_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResponse) ProtoMessage() {}

func (x *ConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_go_convert_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResponse.ProtoReflect.Descriptor instead.
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return file_proto_go_convert_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertResponse) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

func (x *ConvertResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type ChecksumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yaml          string                 `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksumRequest) Reset() {
	*x = ChecksumRequest{}
	mi := &file_proto_go_convert_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksumRequest) ProtoMessage() {}

func (x *ChecksumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_go_convert_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksumRequest.ProtoReflect.Descriptor instead.
func (*ChecksumRequest) Descriptor() ([]byte, []int) {
	return file_proto_go_convert_service_proto_rawDescGZIP(), []int{2}
}

func (x *ChecksumRequest) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

type ChecksumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      string                 `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksumResponse) Reset() {
	*x = ChecksumResponse{}
	mi := &file_proto_go_convert_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksumResponse) ProtoMessage() {}

func (x *ChecksumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_go_convert_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksumResponse.ProtoReflect.Descriptor instead.
func (*ChecksumResponse) Descriptor() ([]byte, []int) {
	return file_proto_go_convert_service_proto_rawDescGZIP(), []int{3}
}

func (x *ChecksumResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

var File_proto_go_convert_service_proto protoreflect.FileDescriptor

const file_proto_go_convert_service_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/go_convert_service.proto\x12\x1fio.harness.pms.conversion.proto\"\xf6\x03\n" +
	"\x0eConvertRequest\x12L\n" +
	"\ventity_type\x18\x01 \x01(\x0e2+.io.harness.pms.conversion.proto.EntityTypeR\n" +
	"entityType\x12\x12\n" +
	"\x04yaml\x18\x02 \x01(\tR\x04yaml\x12y\n" +
	"\x14template_ref_mapping\x18\x03 \x03(\v2G.io.harness.pms.conversion.proto.ConvertRequest.TemplateRefMappingEntryR\x12templateRefMapping\x12y\n" +
	"\x14pipeline_ref_mapping\x18\x04 \x03(\v2G.io.harness.pms.conversion.proto.ConvertRequest.PipelineRefMappingEntryR\x12pipelineRefMapping\x1aE\n" +
	"\x17TemplateRefMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17PipelineRefMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x0fConvertResponse\x12\x12\n" +
	"\x04yaml\x18\x01 \x01(\tR\x04yaml\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\"%\n" +
	"\x0fChecksumRequest\x12\x12\n" +
	"\x04yaml\x18\x01 \x01(\tR\x04yaml\".\n" +
	"\x10ChecksumResponse\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\tR\bchecksum*7\n" +
	"\n" +
	"EntityType\x12\f\n" +
	"\bPIPELINE\x10\x00\x12\f\n" +
	"\bTEMPLATE\x10\x01\x12\r\n" +
	"\tINPUT_SET\x10\x022\xe8\x03\n" +
	"\x10GoConvertService\x12t\n" +
	"\x0fConvertPipeline\x12/.io.harness.pms.conversion.proto.ConvertRequest\x1a0.io.harness.pms.conversion.proto.ConvertResponse\x12t\n" +
	"\x0fConvertTemplate\x12/.io.harness.pms.conversion.proto.ConvertRequest\x1a0.io.harness.pms.conversion.proto.ConvertResponse\x12t\n" +
	"\x0fConvertInputSet\x12/.io.harness.pms.conversion.proto.ConvertRequest\x1a0.io.harness.pms.conversion.proto.ConvertResponse\x12r\n" +
	"\vGetChecksum\x120.io.harness.pms.conversion.proto.ChecksumRequest\x1a1.io.harness.pms.conversion.proto.ChecksumResponseBF\n" +
	"\x1fio.harness.pms.conversion.protoP\x01Z!github.com/drone/go-convert/protob\x06proto3"

var (
	file_proto_go_convert_service_proto_rawDescOnce sync.Once
	file_proto_go_convert_service_proto_rawDescData []byte
)

func file_proto_go_convert_service_proto_rawDescGZIP() []byte {
	file_proto_go_convert_service_proto_rawDescOnce.Do(func() {
		file_proto_go_convert_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_go_convert_service_proto_rawDesc), len(file_proto_go_convert_service_proto_rawDesc)))
	})
	return file_proto_go_convert_service_proto_rawDescData
}

var file_proto_go_convert_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_go_convert_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_go_convert_service_proto_goTypes = []any{
	(EntityType)(0),          // 0: io.harness.pms.conversion.proto.EntityType
	(*ConvertRequest)(nil),   // 1: io.harness.pms.conversion.proto.ConvertRequest
	(*ConvertResponse)(nil),  // 2: io.harness.pms.conversion.proto.ConvertResponse
	(*ChecksumRequest)(nil),  // 3: io.harness.pms.conversion.proto.ChecksumRequest
	(*ChecksumResponse)(nil), // 4: io.harness.pms.conversion.proto.ChecksumResponse
	nil,                      // 5: io.harness.pms.conversion.proto.ConvertRequest.TemplateRefMappingEntry
	nil,                      // 6: io.harness.pms.conversion.proto.ConvertRequest.PipelineRefMappingEntry
}
var file_proto_go_convert_service_proto_depIdxs = []int32{
	0, // 0: io.harness.pms.conversion.proto.ConvertRequest.entity_type:type_name -> io.harness.pms.conversion.proto.EntityType
	5, // 1: io.harness.pms.conversion.proto.ConvertRequest.template_ref_mapping:type_name -> io.harness.pms.conversion.proto.ConvertRequest.TemplateRefMappingEntry
	6, // 2: io.harness.pms.conversion.proto.ConvertRequest.pipeline_ref_mapping:type_name -> io.harness.pms.conversion.proto.ConvertRequest.PipelineRefMappingEntry
	1, // 3: io.harness.pms.conversion.proto.GoConvertService.ConvertPipeline:input_type -> io.harness.pms.conversion.proto.ConvertRequest
	1, // 4: io.harness.pms.conversion.proto.GoConvertService.ConvertTemplate:input_type -> io.harness.pms.conversion.proto.ConvertRequest
	1, // 5: io.harness.pms.conversion.proto.GoConvertService.ConvertInputSet:input_type -> io.harness.pms.conversion.proto.ConvertRequest
	3, // 6: io.harness.pms.conversion.proto.GoConvertService.GetChecksum:input_type -> io.harness.pms.conversion.proto.ChecksumRequest
	2, // 7: io.harness.pms.conversion.proto.GoConvertService.ConvertPipeline:output_type -> io.harness.pms.conversion.proto.ConvertResponse
	2, // 8: io.harness.pms.conversion.proto.GoConvertService.ConvertTemplate:output_type -> io.harness.pms.conversion.proto.ConvertResponse
	2, // 9: io.harness.pms.conversion.proto.GoConvertService.ConvertInputSet:output_type -> io.harness.pms.conversion.proto.ConvertResponse
	4, // 10: io.harness.pms.conversion.proto.GoConvertService.GetChecksum:output_type -> io.harness.pms.conversion.proto.ChecksumResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_go_convert_service_proto_init() }
func file_proto_go_convert_service_proto_init() {
	if File_proto_go_convert_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_go_convert_service_proto_rawDesc), len(file_proto_go_convert_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_go_convert_service_proto_goTypes,
		DependencyIndexes: file_proto_go_convert_service_proto_depIdxs,
		EnumInfos:         file_proto_go_convert_service_proto_enumTypes,
		MessageInfos:      file_proto_go_convert_service_proto_msgTypes,
	}.Build()
	File_proto_go_convert_service_proto = out.File
	file_proto_go_convert_service_proto_goTypes = nil
	file_proto_go_convert_service_proto_depIdxs = nil
}
