pipeline {
    agent any
    stages {
        stage('Generate Coverage Report') {
            steps {
                sh 'mvn clean cobertura:cobertura'
            }
        }
        stage('Publish Coverage Report') {
            steps {
                script {
                    cobertura coberturaReportFile: '**/coverage.xml',
                    classCoverageTargets: '70, 0, 0',
                    conditionalCoverageTargets: '65, 66, 67',
                    failUnhealthy: false,
                    failUnstable: false,
                    fileCoverageTargets: '80, 0, 0',
                    lineCoverageTargets: '75, 76, 77',
                    methodCoverageTargets: '72, 73, 74',
                    packageCoverageTargets: '80, 0, 0',
                }
            }
        }
    }
}
