pipeline {
    agent any
    stages {
        stage('File') {
            steps {
                fileOperations([
                    folderCreateOperation(folderPath: 'src/create')
                ])
            }
        }
    }
}