pipeline {
    agent any
    stages {
        stage("readfile") {
            steps {
                script
                {
                    def props = readYaml file: "abc.yml"
                }
                
            }
        }
    }
}