pipeline {
    agent any

    stages {
        stage('fail') {
            steps {
                sh 'exit 0'
            }
        }
    }
    post {
        always {
            emailext subject: 'Email ${BUILD_STATUS}', body: 'Email ${BUILD_NUMBER}', to: 'first@example.com second@example.com'
        }
    }
}