pipeline {
    agent any

    stages {
        stage('read file') {
            steps {
                readJSON file: '/Users/rakshith/Downloads/IntermediateJson/BasicPipe.json'
            }
        }
    }
}